FROM fusuf/whatsasena:latest

RUN  /https://github.com/Pikkachu4322/Sophiaroot/WhatsAsenaDuplicated
WORKDIR /root/WhatsAsenaDuplicated/
ENV TZ=Europe/Istanbulhttps://github.com/Pikkachu4322/Sophia
RUN npm install supervisor -g
RUN yarn install --no-audit

CMD ["node", "bot.js"]
